// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go-template/internals/model"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Ping provides a mock function with given fields: ctx, input
func (_m *Service) Ping(ctx context.Context, input model.Ping) (*model.Pong, error) {
	ret := _m.Called(ctx, input)

	var r0 *model.Pong
	if rf, ok := ret.Get(0).(func(context.Context, model.Ping) *model.Pong); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pong)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Ping) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
